# -*- coding: utf-8 -*-
"""BFS/DFS.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1QKlgKrC0nPC-47ncx2Ehzo8wvcUuspDc
"""

from collections import deque, defaultdict

# Graph represented as adjacency list
graph = {
    "Haripur": ["Tarbella", "Khanpur"],
    "Tarbella": ["Haripur", "Swabi", "Khanpur"],
    "Khanpur": ["Haripur", "Tarbella", "Topi"],
    "Topi": ["Khanpur", "Swabi"],
    "Swabi": ["Tarbella", "Topi"]
}

# BFS to find shortest path from source to destination
def bfs_shortest_path(graph, start, goal):
    visited = set()
    queue = deque([[start]])

    while queue:
        path = queue.popleft()
        node = path[-1]

        if node == goal:
            return path

        if node not in visited:
            for neighbor in graph[node]:
                new_path = list(path)
                new_path.append(neighbor)
                queue.append(new_path)
            visited.add(node)
    return None

# DFS to find connected components (or full traversal)
def dfs(graph, node, visited):
    visited.add(node)
    print(node, end=" → ")
    for neighbor in graph[node]:
        if neighbor not in visited:
            dfs(graph, neighbor, visited)

# Run BFS
source = "Haripur"
destination = "Swabi"
shortest_path = bfs_shortest_path(graph, source, destination)
print("Shortest path from", source, "to", destination, "is:", " → ".join(shortest_path))

# Run DFS
print("\nDFS Traversal (starting from Haripur):")
visited_set = set()
dfs(graph, "Haripur", visited_set)

import networkx as nx
import matplotlib.pyplot as plt

# Define the edges based on your input
edges = [
    ("Haripur", "Tarbella"),
    ("Haripur", "Khanpur"),
    ("Tarbella", "Swabi"),
    ("Tarbella", "Khanpur"),
    ("Khanpur", "Topi"),
    ("Topi", "Swabi")
]

# Create an undirected graph
G = nx.Graph()
G.add_edges_from(edges)

# Draw the graph
plt.figure(figsize=(10, 7))
pos = nx.spring_layout(G, seed=42)  # Position layout
nx.draw(G, pos, with_labels=True, node_size=2000, node_color='skyblue', font_size=12, font_weight='bold', edge_color='gray')
plt.title("Graph of Cities (Haripur to Swabi)", fontsize=14)
plt.show()